In [ ]:
import networkx as nx
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import operator
import random as rd
import time


In [75]:
from numpy import zeros

#Data input
z=zeros([10748,10748])
with open ("links.txt","r") as links:
    
#Create Adjacency Matrix
        for lines in links.readlines():
            node=lines.split(',')
            journal_citing = int(node[0])
            journal_cited = int(node[1])
            number_citation = int(node[2])
            z[journal_citing][journal_cited]=number_citation

print(z)

[[  34.    0.    0. ...    0.    0.    0.]
 [   0.   21.    0. ...    0.    0.    0.]
 [   0.    0. 1594. ...    0.    0.    0.]
 ...
 [   0.    0.    0. ...   20.    0.    0.]
 [   0.    0.    0. ...    0.    0.    0.]
 [   0.    0.    0. ...    0.    0.   40.]]


In [76]:
#1.3 Modifying the Adjacency Matrix

# set the diagonal of Z to zero (i.e., we set all of the entries Zii = 0)
np.fill_diagonal(z,0)
np.seterr(invalid='ignore')

#we normalize the columns of the matrix
def normalize(matrix):
    global columntotal 
    columntotal = np.sum(matrix, axis=0)
    normal = np.divide(matrix,columntotal)
    normal = np.nan_to_num(normal)
   # matrix[np.isnan(matrix)]=0
    return(normal)
H= normalize(z)
#function

#H=z[0]


H
#H.shape


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [77]:
#1.4 identifying the dangling nodes
d = []
for i in range(len(columntotal)):
    if (columntotal[i] == 0):
        d.append(1)
    else:
        d.append(0)
print(d)
d_array = np.array(d)
np.sum(d_array)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

56

In [78]:
#create article vector
def Article():
    matrix= np.ones((10748,1))
    total = matrix.sum()
    return(matrix)
a=Article()
print(a)

#np.transpose(a)
#a.T
print(np.shape(a))
#resource https://github.com/huibrm/Page-Rank/blob/master/Page_Rank_lab-1-1.py

[[1.]
 [1.]
 [1.]
 ...
 [1.]
 [1.]
 [1.]]
(10748, 1)


In [79]:
#practice eichen
testMatrix = np.array([[1,0,2,0,4,3],[3,0,1,1,0,0],[2,0,4,0,1,0],[0,0,1,0,0,1],[8,0,3,0,5,2],[0,0,0,0,0,0]])
testz=np.fill_diagonal(testMatrix,0)
test_a_vector = np.array([[3/14,2/14,5/14,1/14,2/14,1/14]]).T

test_start_vector = np.array([[1/6]*6]).T

danglingnodes = np.array([[0,1,0,0,0,0]])
print(testMatrix)
normalizedtest=normalize(testMatrix)

print(columntotal) 
print(normalizedtest)

[[0 0 2 0 4 3]
 [3 0 1 1 0 0]
 [2 0 0 0 1 0]
 [0 0 1 0 0 1]
 [8 0 3 0 0 2]
 [0 0 0 0 0 0]]
[13  0  7  1  5  6]
[[0.         0.         0.28571429 0.         0.8        0.5       ]
 [0.23076923 0.         0.14285714 1.         0.         0.        ]
 [0.15384615 0.         0.         0.         0.2        0.        ]
 [0.         0.         0.14285714 0.         0.         0.16666667]
 [0.61538462 0.         0.42857143 0.         0.         0.33333333]
 [0.         0.         0.         0.         0.         0.        ]]


In [111]:
Alpha_constant  = 0.85
Epsilon_constant = 0.00001

α=Alpha_constant

In [130]:
#π(k+1) = αH π(k) + [αd.π(k) + (1 −α)]a for influence vector

first_iteration = np.ones(len(H)) / len(H)

def Eigenvector_iterator(firstiter,normalized,article,dangle):
#create variable to iterate on the first one
    count = firstiter
    iterationcount = 0
#(pi at k+1) - (pi at k) is greater than epsilon
    remainingL1 = Epsilon_constant
    while remainingL1 >= Epsilon_constant:
#find the absolute value (l1 distance)  np.absolute and then sum of np.absolute
#create variable to identify current iteration
        newvector=(α*np.matmul(normalized,count))+(((α*np.matmul(dangle,count)+(1-α)))*article)
                                   
        remainingL1=(np.sum(np.absolute(newvector - count)))
#count needs to change to newvector so it changes for the next iteration        
        count=newvector
    
        iterationcount = iterationcount + 1
    print(iterationcount,"iterations")
    return newvector, iterationcount


In [131]:
#practice on test set
print(Eigenvector_iterator(test_start_vector,normalizedtest,test_a_vector,danglingnodes))

18 iterations
(array([[0.30402138],
       [0.16360304],
       [0.18979616],
       [0.04661906],
       [0.27531309],
       [0.02064727]]), 18)


In [ ]:
#calculate the influence vector
#π(k+1) = αH π(k) + [αd.π(k) + (1 −α)]a

print(Eigenvector_iterator(first_iteration,H,a,d))
  

In [90]:
print(α*np.matmul(H, test_start_vector))
print(test_start_vector)

[[0.22464286]
 [0.19459707]
 [0.05012821]
 [0.04384921]
 [0.195116  ]
 [0.        ]]
[[0.16666667]
 [0.16666667]
 [0.16666667]
 [0.16666667]
 [0.16666667]
 [0.16666667]]


In [ ]:
#calculating Eigenfactor(EFi)
startTime = time.time()
EF = 100*np.dot(H,newvector)/np.dot(H,newvector).sum(axis=0)
print(EF)
print(iterationcount + "iterations")

i=iteration
# Print top 20 Articles 
print("Top 20 EF journals",np.argsort()[-20:][::-1]

#print time taken
print(time.time() - startTime + " seconds")

#reference https://github.com/huibrm/Page-Rank/blob/master/Page_Rank_lab-1-1.py